allowBuilds:
  node-gtk: true
  node-pty: true
  usocket: false
packages:
  - packages/*
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - '@o-feod/eslint-structure-plugin@0.1.3'
  - '@o-feod/oxlint-structure-plugin@0.1.3'
